### ISSUE TITLE
Error running create-rule: Cannot read properties of undefined (reading 'offset')

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [gajus/eslint-plugin-jsdoc#1003]
## Expected behavior

I'd like to be able to scaffold a new rule (#1000) with the nice templating built into this package.

## Actual behavior

```plaintext
$ npm run create-rule informative-docs

> eslint-plugin-jsdoc@1.0.0 create-rule
> babel-node ./src/bin/generateRule.js

ruleNames [
  ...
]
/Users/josh/repos/eslint-plugin-jsdoc/src/bin/generateRule.js:146
      item.offset += item.matchedLine.length;
      ^

TypeError: Cannot read properties of undefined (reading 'offset')
    at replaceInOrder (/Users/josh/repos/eslint-plugin-jsdoc/src/bin/generateRule.js:187:7)
    at /Users/josh/repos/eslint-plugin-jsdoc/src/bin/generateRule.js:218:3

Node.js v18.7.0
```

## Environment

- Node version: 18.7.0
- ESLint version n/a
- `eslint-plugin-jsdoc` version: `main` -> 1.0.0?

**Comment by brettz9** [comment]
Fixed now on `main`. Had to accommodate the changes to index in the recent PR for recommended-typescript. All good now.

**Comment by JoshuaKGoldberg** [comment]
😂 hoisted on my own petard! Thanks!
