### ISSUE TITLE
Running `npm run create-readme` fails

### ISSUE THREAD

**Issue by kraenhansen** [gajus/eslint-plugin-jsdoc#1057]
Running `npm run create-readme` yields the following error:

```
Error: Branch ("main") definition does not exist in the config.
    at Object.gitinfo.getRemoteUrl (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/node_modules/gitinfo/dist/gitinfo.js:100:13)
    at Object.gitinfo.getUsername (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/node_modules/gitinfo/dist/gitinfo.js:132:53)
    at Object.gitinfo.getGithubUrl (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/node_modules/gitinfo/dist/gitinfo.js:51:44)
    at Object.helper.compile (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/node_modules/gitdown/dist/helpers/gitinfo.js:36:41)
    at Object.gitdown.resolveURLs (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/node_modules/gitdown/dist/gitdown.js:113:35)
    at Object.gitdown.get (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/node_modules/gitdown/dist/gitdown.js:56:19)
    at async Promise.all (index 0)
    at generateDocs (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/src/bin/generateDocs.js:123:23)
    at async Promise.all (index 0)
    at generateDocsAndWriteToDisk (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/src/bin/generateDocs.js:208:7)
    at main (/Users/kraen.hansen/Projects/eslint-plugin-jsdoc/src/bin/generateDocs.js:247:7)
```

## Environment

- Node version: v18.9.0
- ESLint version: N/A
- `eslint-plugin-jsdoc` version: ec278a292ed343ac875359d66acc4dd81301ec23

**Comment by brettz9** [comment]
Per https://github.com/gajus/gitdown/issues/27 , it looks like this can occur when there is no remote URL for the branch (maybe because `master` is in use on gajus?). Gitdown apparently uses this for URL generation (not sure when/how), so I guess the remote should be set. See also https://github.com/gajus/gitdown/issues/57 for an open issue.

**Comment by kraenhansen** [comment]
Thanks - this solved it for me.
Feel free to close this issue or leave it open, as it did cause some confusion and would probably be good to find a more permanent solution for.

**Comment by brettz9** [comment]
Good to hear. I think those interested can track a possible fix at https://github.com/gajus/gitdown/issues/57 .
