### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by kurtextrem** [gajus/eslint-plugin-jsdoc#129]
```
TypeError: Cannot read property 'type' of null
    at SourceCode.getJSDocComment (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\util\source-code.js:357:28)
    at checkJsdoc (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint-plugin-jsdoc\dist\iterateJsdoc.js:157:34)
    at listeners.(anonymous function).forEach.listener (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\util\safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\util\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\util\node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (C:\Users\Jacob\AppData\Roaming\npm\node_modules\eslint\lib\linter.js:750:28)
```

Code:
```
import Player from '../Player'
import { promiseAfter } from '../utils/Utils'

export default class Worm extends Player {
	constructor(game, id) {
		super(game, id)

		this.speed = 0.5
		this.impact = 0.75
	}

	draw() {
		this.game.engine.drawImage(
			this.game.assets.worm,
			256,
			256,
			0,
			0,
			this.tweenX,
			this.tweenY,
			this.width
		)
	}

	handleMoleHit(obj) {
		const impact = obj.impact

		if (!this.canMove) return // we don't want to enable abuse, so if the worm can't move, make it 'invincible' to other hits

		if (impact / this.impact > 2 && this.canMove) {
			this.canMove = false
			promiseAfter(obj.impactTicks)
				.then(() => (this.canMove = true))
				.catch(e => e)
			return
		}

		this.impactAndRestoreSpeedAfter(impact, obj.impactTicks)
	}
}

export const isWorm = obj => obj instanceof Worm
```

I think the error appeared after I had added `.catch(e => e)`

Using latest node, latest eslint and latest eslint-plugin-jsdoc version

**Comment by brettz9** [comment]
I'm not seeing this issue against `master`, at least with the config I tested. Can you please confirm whether you are still seeing the issue, and if so, what your config/rules are?

**Comment by brettz9** [comment]
And be sure you have this set:

```js
      parserOptions: {
        sourceType: 'module'
      }
```
