### ISSUE TITLE
Can't Lint Files With Class Decorators: TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by arottersman** [gajus/eslint-plugin-jsdoc#376]
**Bug Overview 🐛**
I'm unable to run `eslint` on files with class decorators when I configure certain `require` options for the `jsdoc/require-jsdoc`.

**Failing `.eslintrc.json` Config**

Note: If I remove the `require` block from the `jsdoc/require-jsdoc` options, the file is linted as expected.

```json
{
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "commonjs": true,
    "es6": true,
    "node": true
  },
  "extends": "eslint:recommended",
  "plugins": ["import", "jsx-a11y", "react", "jsdoc"],
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "jsdoc/require-jsdoc": [1, {
      "publicOnly": true,
      "require": {
        "ArrowFunctionExpression": true,
        "FunctionExpression": false,
        "ClassDeclaration": true,
        "ClassExpression": true
      }
    }]
  }
}
```
**Relevant Versions**
```json
{
    "@babel/core": "^7.4.5",
    "babel-eslint": "^10.0.2",
    "eslint": "^6.3.0",
    "eslint-plugin-jsdoc": "^15.9.1"
}
```
**Error Message**
```
❯ yarn eslint src/fileWithClassDecorators.js
yarn run v1.16.0
$ /<...my local path>/node_modules/.bin/eslint src
TypeError: Cannot read property 'type' of undefined
Occurred while linting ./src/fileWithClassDecorators.js:4
    at getSymbol (/<...my local path>/node_modules/eslint-plugin-jsdoc/dist/exportParser.js:73:16)
    at /Users/alicerottersman/dev/odentech/operator/node_modules/eslint-plugin-jsdoc/dist/exportParser.js:145:27
    at Array.forEach (<anonymous>)
    at getSymbol (/<...my local path>/node_modules/eslint-plugin-jsdoc/dist/exportParser.js:144:25)
    at createSymbol (/<...my local path>/node_modules/eslint-plugin-jsdoc/dist/exportParser.js:194:31)
    at /<...my local path>/node_modules/eslint-plugin-jsdoc/dist/exportParser.js:327:26
    at Array.forEach (<anonymous>)
    at mapVariables (/<...my local path>/node_modules/eslint-plugin-jsdoc/dist/exportParser.js:324:27)
    at /<...my local path>/node_modules/eslint-plugin-jsdoc/dist/exportParser.js:302:13
    at Array.forEach (<anonymous>)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Failing File**
```js
import { inject, observer } from 'mobx-react';
import React, { Component } from 'react';

@inject('events')
@observer
class Entry extends Component {
}
```

**Comment by brettz9** [comment]
I'm not able to replicate adding the following to our test cases:

```js
{
    code: `
      import { inject, observer } from 'mobx-react';
      import React, { Component } from 'react';

      @inject('events')
      @observer
      class Entry extends Component {
      }
    `,
    options: [
      {
        publicOnly: true,
        require: {
          ArrowFunctionExpression: true,
          ClassDeclaration: true,
          ClassExpression: true,
          FunctionExpression: false,
        },
      },
    ],
    parser: require.resolve('babel-eslint'),
    parserOptions: {
      sourceType: 'module',
    },
  }
```

Can you replicate without your `extends` or `plugins` (and `env`)?  I am using babel-eslint 10.0.3, so you might want to upgrade if you haven't already.

**Comment by arottersman** [comment]
Interesting! Yes, still able to recreate after upgrading to babel-eslint 10.0.3 and updating `.eslintrc.json` to:
```json
{
  "parser": "babel-eslint",
  "plugins": ["jsdoc"],
  "parserOptions": {
    "sourceType": "module"
  },
  "rules": {
    "jsdoc/require-jsdoc": [1, {
      "publicOnly": true,
      "require": { "ClassDeclaration": true }
    }]
  }
}
```

**Comment by brettz9** [comment]
No, I'm not replicating with this test case for `require-jsdoc`:

```js
{
    code: `
    import { inject, observer } from 'mobx-react';
    import React, { Component } from 'react';

    @inject('events')
    @observer
    class Entry extends Component {
    }
    `,
    options: [{
      publicOnly: true,
      require: {ClassDeclaration: true},
    }],
    parser: require.resolve('babel-eslint'),
    parserOptions: {
      sourceType: 'module',
    },
  }
```

Did you check your `node_modules` to ensure that the version of eslint-plugin-jsdoc is indeed 15.9.1?

If it is, maybe you could try logging in the `exportParser.js` file to find out, e.g., what `prop` is on line 145 such that `prop.value` is coming out undefined.

**Comment by brettz9** [comment]
@arottersman : I'll close this issue in favor of #378, as that one I can replicate and seems to be hinting at the same issue, but if your issue still doesn't go away after that is fixed, I'd suggest reopening this issue (or if you prefer, filing a new issue). For now, I'd recommend your subscribing to that issue, so you can be informed of any updates.
