### ISSUE TITLE
Update 18.1.1 broke the lint

### ISSUE THREAD

**Issue by zhaparoff** [gajus/eslint-plugin-jsdoc#433]
Updating JSDoc plugin to `18.1.1` breaks the lint with the following error:
```
> eslint src --ext .ts

TypeError: Cannot read property 'endsWith' of undefined
Occurred while linting C:\_Work\Code\GitHub\xrm-alerts\src\ts\alert.ts:18
    at Object.report.line [as fix] (C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint-plugin-jsdoc\dist\rules\newlineAfterDescription.js:46:80)
    at normalizeFixes (C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint\lib\linter\report-translator.js:176:28)
    at C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint\lib\linter\report-translator.js:278:49
    at Object.report (C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint\lib\linter\linter.js:905:41)
    at report (C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint-plugin-jsdoc\dist\iterateJsdoc.js:388:13)
    at _default.iterateAllJsdocs (C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint-plugin-jsdoc\dist\rules\newlineAfterDescription.js:44:7)
    at C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint-plugin-jsdoc\dist\iterateJsdoc.js:444:13
    at Array.forEach (<anonymous>)
    at Program (C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint-plugin-jsdoc\dist\iterateJsdoc.js:433:20)
    at C:\_Work\Code\GitHub\xrm-alerts\node_modules\eslint\lib\linter\safe-emitter.js:45:58
```
Meanwhile, `18.1.0` works fine.

Source: https://github.com/zhaparoff/xrm-alerts/blob/master/src/ts/alert.ts

OS: `Win10 x64 1903`
node: `13.1.0`
npm: `6.13.1`

**Comment by brettz9** [comment]
Hopefully that does the trick...

**Comment by zhaparoff** [comment]
Yes, it is working now.
