### ISSUE TITLE
18.1.2 TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by donwalling** [gajus/eslint-plugin-jsdoc#436]
my company's js required file header is of the form
/**********
 *
 */
function () {}

which breaks on 18.1.2 with

     TypeError: Cannot read property 'trim' of undefined
Occurred while linting <input>:5
      at iterator (src/rules/newlineAfterDescription.js:14:26)
      at forEach (src/iterateJsdoc.js:445:13)
      at Array.forEach (<anonymous>)
      at Program (src/iterateJsdoc.js:433:20)
      at /Users/dwalling/git/donwalling/eslint-plugin-jsdoc/node_modules/eslint/lib/linter/safe-emitter.js:45:58
      at Array.forEach (<anonymous>)
      at Object.emit (node_modules/eslint/lib/linter/safe-emitter.js:45:38)
      at NodeEventGenerator.applySelector (node_modules/eslint/lib/linter/node-event-generator.js:254:26)
      at NodeEventGenerator.applySelectors (node_modules/eslint/lib/linter/node-event-generator.js:283:22)
      at NodeEventGenerator.enterNode (node_modules/eslint/lib/linter/node-event-generator.js:297:14)
      at CodePathAnalyzer.enterNode (node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
      at /Users/dwalling/git/donwalling/eslint-plugin-jsdoc/node_modules/eslint/lib/linter/linter.js:936:32
      at Array.forEach (<anonymous>)
      at runRules (node_modules/eslint/lib/linter/linter.js:931:15)
      at Linter._verifyWithoutProcessors (node_modules/eslint/lib/linter/linter.js:1157:31)
      at Linter.verify (node_modules/eslint/lib/linter/linter.js:1220:21)
      at runRuleForItem (node_modules/eslint/lib/rule-tester/rule-tester.js:409:37)
      at testValidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:457:28)
      at Context.<anonymous> (node_modules/eslint/lib/rule-tester/rule-tester.js:626:25)
      at processImmediate (internal/timers.js:439:21)

**Comment by donwalling** [comment]
a failing test:

diff --git a/test/rules/assertions/newlineAfterDescription.js b/test/rules/assertions/newlineAfterDescription.js
index 7237176..709fd82 100644
--- a/test/rules/assertions/newlineAfterDescription.js
+++ b/test/rules/assertions/newlineAfterDescription.js
@@ -287,5 +287,17 @@ export default {
        */\r
       `,
     },
+    {
+      code: `
+      /***
+       *
+       */
+      function quux () {
+
+      }`,
+      options: [
+        'always',
+      ],
+    },
   ],
 };

**Comment by donwalling** [comment]
18.1.0 is fine

**Comment by brettz9** [comment]
Fixed by https://github.com/gajus/eslint-plugin-jsdoc/releases/tag/v18.1.3 (forgot to link the commit to this issue).

Thank you for the very helpful background, test case, and version info. It turns out the real issue on our end was mistakenly treating 3 or more asterisks for a jsdoc block (or blocks not terminated by whitespace such as `/***/`) as jsdoc. Such is not valid jsdoc, however, per the [spec](https://jsdoc.app/about-getting-started.html) and code subsequent to filtering out non-jsdoc should always be able to assume `jsdoc.description` is a string per our use of `comment-parser`. This should now be fixed.

**Comment by donwalling** [comment]
@brettz9  thanks for taking care of it so quickly!
