### ISSUE TITLE
Possible Bug. TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by ernestostifano** [gajus/eslint-plugin-jsdoc#501]
I get the following error:
```
TypeError: Cannot read property 'map' of undefined
Occurred while linting someFile.js:14

TypeError: Cannot read property 'map' of undefined
Occurred while linting someFile.js:14
    at Object.getFunctionParameterNames (/some-path/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:45:30)
    at checkJsDoc (/some-path/node_modules/eslint-plugin-jsdoc/dist/rules/requireJsdoc.js:147:60)
    at ClassDeclaration (/some-path/node_modules/eslint-plugin-jsdoc/dist/rules/requireJsdoc.js:217:9)
    at /some-path/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/some-path/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/some-path/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/some-path/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (/some-path/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (/some-path/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:634:23)
Process finished with exit code -1
```
while using the following rule:
```
{
'jsdoc/require-jsdoc': [
        'warn',
        {
            require: {
                ArrowFunctionExpression: true,
                ClassDeclaration: true,
                ClassExpression: true,
                FunctionDeclaration: true,
                FunctionExpression: false,
                MethodDefinition: true
            },
            exemptEmptyFunctions: true
        }
    ]
}
```

However, the error goes away and everything works as expected when the `exemptEmptyFunctions ` option is set to `false` or if the `require.ClassDeclaration` option is set to `false`. So there must be some kind of conflict between those two options.

It is **important** to note that the linted file uses React + Flow. Other files in the repo that does not use React nor Flow, doesn't have this issue.

`someFile.js:14` corresponds to a class declaration being exported like:

```
export class MyClass {
    someProperty: boolean; // Flow type annotation.
    [...]
}
```

My override configuration for this files is:

```
// REACT + FLOW PACKAGES
        {
            files: [...],
            parserOptions: {
                ecmaFeatures: {
                    jsx: true
                }
            },
            plugins: ['flowtype', 'react'],
            extends: [
                'prettier/flowtype',
                'prettier/react',
                'plugin:flowtype/recommended',
                'plugin:react/recommended'
            ],
            rules: {
                'jsdoc/check-tag-names': [
                    'warn',
                    {
                        definedTags: ['flow']
                    }
                ],
                'react/require-default-props': 'error'
            },
            settings: {
                flowtype: {
                    onlyFilesWithFlowAnnotation: true
                },
                react: {
                    version: 'detect'
                }
            }
        }
```

However, changes in this configuration seems to not affect the issue. It may only depend on the flow syntax used in the linted file and the first two options as described above.

If more information is needed, please do not hesitate to ask.

Best regards,

Ernesto Stifano

**Comment by brettz9** [comment]
In trying to replicate, I've set up the following config (we shouldn't need to extend or set other rules here, as we want to isolate it to our package):

```js
{
    code: `
    export class MyClass {
      someProperty: boolean; // Flow type annotation.
    }
    `,
    options: [{
      exemptEmptyFunctions: true,
      require: {
        ArrowFunctionExpression: true,
        ClassDeclaration: true,
        ClassExpression: true,
        FunctionDeclaration: true,
        FunctionExpression: false,
        MethodDefinition: true,
      },
    }],
    parserOptions: {
      ecmaFeatures: {
        jsx: true,
      },
      sourceType: 'module',
    },
    plugins: ['flowtype', 'react'],
    settings: {
      flowtype: {
        onlyFilesWithFlowAnnotation: true,
      },
      react: {
        version: 'detect',
      },
    },
  },
```

However, I am getting this error:

```
A fatal parsing error occurred: Parsing error: Unexpected token :
```

Any ideas why that would be occurring despite the fact I've included "flowtype" under `plugins`?

**Comment by brettz9** [comment]
Nevermind, I've gotten it by adding `babel-eslint` as a parser (and removing `plugins` which we don't need to replicate and might not be used by the rule tester anyways).
