### ISSUE TITLE
Crash after upgrading from v24.0.6

### ISSUE THREAD

**Issue by jaydenseric** [gajus/eslint-plugin-jsdoc#536]
Something changed between v24.0.6 and v25.0.0 to cause this exception:

```
Oops! Something went wrong! :(

ESLint: 7.0.0

Error: Unsupported function signature format.
Occurred while linting /[redacted]/graphql-react/src/universal/GraphQL.js:139
    at getParamName (/[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:173:11)
    at /[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:129:16
    at Array.map (<anonymous>)
    at getParamName (/[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:128:32)
    at /[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:177:12
    at Array.map (<anonymous>)
    at Object.getFunctionParameterNames (/[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:176:30)
    at Object.utils.getFunctionParameterNames (/[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:182:32)
    at _default.meta.fixable (/[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/rules/checkParamNames.js:199:40)
    at iterate (/[redacted]/graphql-react/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:491:3)
```

Here is the doclet it has a problem with:

https://github.com/jaydenseric/graphql-react/blob/1bb884d0a9043f84727291c8580ab91fdc9ff196/src/universal/GraphQL.js#L139

**Comment by brettz9** [comment]
This has now been fixed.

However, until #530 may be fixed, note that you will not have the option of disabling the now reporting of destructured params (in your case, `fetchOptions.url` and `fetchOptions.options`).  PR #532 is mostly ready to request this ability to disable; will see about finishing up the necessary work tomorrow.

**Comment by brettz9** [comment]
Feel free to subscribe to #530 for updates (though the title is for `require-param`, it also relates to `check-param-names`).
