### ISSUE TITLE
eslint vscode plugin not working

### ISSUE THREAD

**Issue by danny007in** [gajus/eslint-plugin-jsdoc#882]
```
[Info  - 1:51:35 pm] ESLint server is starting
[Info  - 1:51:36 pm] ESLint server running in node v16.13.0
[Info  - 1:51:36 pm] ESLint server is running.
[Info  - 1:51:38 pm] ESLint library loaded from: C:\wamp64\www\desktop\node_modules\eslint\lib\api.js
[Error - 1:51:38 pm] ESLint stack trace:
[Error - 1:51:38 pm] Error: Invalid Options:
- Unknown options: configFile
- 'configFile' has been removed. Please use the 'overrideConfigFile' option instead.
    at processOptions (C:\wamp64\www\desktop\node_modules\eslint\lib\eslint\eslint.js:281:15)
    at new ESLint (C:\wamp64\www\desktop\node_modules\eslint\lib\eslint\eslint.js:428:34)
    at Object.e.newESLintClass (c:\Users\Daniel\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:167243)
    at Ce (c:\Users\Daniel\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:186299)
    at c:\Users\Daniel\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:180305
    at c:\Users\Daniel\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:181582
```

**Comment by brettz9** [comment]
It looks like you mean to report this to the main ESLint site. This is for the plugin` eslint-plugin-jsdoc`.

**Comment by danny007in** [comment]
in v8 
```
- Unknown options: configFile
- 'configFile' has been removed. Please use the 'overrideConfigFile' option instead.

**Comment by brettz9** [comment]
This is not the repository for ESLint. If it is related to ESLint, it should be at https://github.com/eslint/eslint/issues/ . Please file your issue there.
