### ISSUE TITLE
error while JSDoc type is union

### ISSUE THREAD

**Issue by blephy** [gajus/eslint-plugin-jsdoc#938]
# Description

Hi, while i'm using union type in JSDoc type definition, eslint is crashing : 

```txt
ESLint stack trace:
[Error - 13:20:00] TypeError: Cannot read properties of undefined (reading 'brackets')
Occurred while linting /Users/src/ConfigManager.ts:17
Rule: "jsdoc/check-types"
    at adjustNames (/Users/node_modules/eslint-plugin-jsdoc/dist/rules/checkTypes.js:43:36)
    at getInvalidTypes (/Users/node_modules/eslint-plugin-jsdoc/dist/rules/checkTypes.js:224:7)
    at /Users/node_modules/eslint-plugin-jsdoc/dist/rules/checkTypes.js:247:7
    at _traverse (/Users/node_modules/jsdoc-type-pratt-parser/dist/index.js:2358:59)
    at _traverse (/Users/node_modules/jsdoc-type-pratt-parser/dist/index.js:2365:25)
    at traverse (/Users/node_modules/jsdoc-type-pratt-parser/dist/index.js:2382:9)
    at _default.iterateAllJsdocs (/Users/node_modules/eslint-plugin-jsdoc/dist/rules/checkTypes.js:239:32)
    at iterate (/Users/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:779:3)
    at callIterator (/Users/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:880:7)
    at *:not(Program) (/Users/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:924:11)
```

[Opened issue on jsdoc-type-pratt-parser](https://github.com/jsdoc-type-pratt-parser/jsdoc-type-pratt-parser/issues/145)

## Environment

- Node version: 18.12.1
- ESLint version 8.30.0
- `eslint-plugin-jsdoc` version: 39.6.4

**Comment by brettz9** [comment]
Can you please provide your ESLint config, at least that related to `eslint-plugin-jsdoc`?

**Comment by blephy** [comment]
@brettz9 yes !

```js
Hi @brettz9 

My setup : 

```js
module.exports = {
  env: {
    es2022: true,
  },
  ignorePatterns: ['**/node_modules/**', '**/build/**, **/dist/**', '**/lib/**'],
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    projectFolderIgnoreList: ['**/node_modules/**', '**/build/**, **/dist/**', '**/lib/**'],
  },
  extends: ['plugin:jsdoc/recommended'],
  settings: {
    jsdoc: {
      // mode: 'typescript',
      overrideReplacesDocs: true,
      tagNamePreference: {
        todo: {
          message:
            "We expect immediate perfection, so don't leave to-dos in your code, prefer a Jira task !",
        },
      },
      preferredTypes: {
        any: {
          message: 'Do not use any, use * instead',
          replacement: '*',
        },
        '[]': {
          message: 'Do not use *[], use Array<*> instead',
          replacement: 'Array',
        },
        'Array.<>': {
          message: 'Do not use Array.<*>, use Array<*> instead',
          replacement: 'Array<>',
        },
      },
    },
  },
  overrides: [
    {
      files: ['./**/*.?(c|m)js', './**/__tests__/**/*', './**/?(*.)+(spec|test).?(c|m)[jt]s?(x)'],
      rules: {
        'jsdoc/require-jsdoc': 'off',
      },
    },
  ],
  rules: {
    'jsdoc/require-description-complete-sentence': 'off',
    'jsdoc/no-undefined-types': 'error',
    'jsdoc/require-description': 'error',
    'jsdoc/check-access': 'error',
    'jsdoc/check-alignment': 'error',
    'jsdoc/check-indentation': 'error',
    'jsdoc/check-line-alignment': 'error',
    'jsdoc/check-param-names': ['error', { checkRestProperty: true, enableFixer: true }],
    'jsdoc/check-property-names': 'error',
    'jsdoc/check-syntax': 'error',
    'jsdoc/check-tag-names': 'error',
    'jsdoc/check-values': 'error',
    'jsdoc/check-types': ['error', { unifyParentAndChildTypeChecks: true }],
    'jsdoc/valid-types': 'error',
    'jsdoc/empty-tags': 'error',
    'jsdoc/implements-on-classes': 'error',
    'jsdoc/newline-after-description': 'error',
    'jsdoc/require-jsdoc': [
      'error',
      {
        require: {
          ArrowFunctionExpression: true,
          ClassDeclaration: true,
          ClassExpression: true,
          FunctionDeclaration: true,
          FunctionExpression: true,
          MethodDefinition: true,
        },
        contexts: [
          'ArrowFunctionExpression',
          'FunctionDeclaration',
          'FunctionExpression',
          'MethodDefinition',
          // 'Property',
          'PropertyDefinition',
          'TSDeclareFunction',
          'TSEnumDeclaration',
          'TSInterfaceDeclaration',
          'TSMethodSignature',
          'TSInterfaceDeclaration TSPropertySignature',
          'TSTypeAliasDeclaration',
          // 'VariableDeclaration',
        ],
        checkGetters: true,
        checkSetters: true,
        checkConstructors: true,
        enableFixer: true,
      },
    ],
    'jsdoc/require-param': 'error',
    'jsdoc/require-param-description': 'error',
    'jsdoc/require-param-name': 'error',
    'jsdoc/require-param-type': 'error',
    'jsdoc/require-throws': 'error',
    'jsdoc/require-returns': ['error', { forceReturnsWithAsync: true }],
    'jsdoc/require-returns-check': 'error',
    'jsdoc/require-returns-description': 'error',
    'jsdoc/require-returns-type': 'error',
    'jsdoc/require-property': 'error',
    'jsdoc/require-property-description': 'error',
    'jsdoc/require-property-name': 'error',
    'jsdoc/require-yields': 'error',
    'jsdoc/require-yields-check': 'error',
  },
}
```

```

**Comment by brettz9** [comment]
@gajus: Any idea why Travis builds are not being triggered? https://app.travis-ci.com/github/gajus/eslint-plugin-jsdoc
