### ISSUE TITLE
SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by its-dibo** [gajus/eslint-plugin-jsdoc#992]
when I run eslint, the follwing error happens and caused by `eslint-plugin-jsdoc`
```
Oops! Something went wrong! :(

ESLint: 8.34.0

D:\projects\dev\dibo\node_modules\eslint-plugin-jsdoc\dist\iterateJsdoc.js:292
  })() ?? jsdoc.source.findIndex(({
        ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\projects\dev\dibo\node_modules\eslint-plugin-jsdoc\dist\rules\checkAccess.js:7:44)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
husky - pre-commit hook exited with code 1 (error)
```

environments:
- eslint-plugin-jsdoc version 40.0.1
- the project is esm

**Comment by brettz9** [comment]
Which version of Node are you using?

**Comment by mikeweitz** [comment]
Seeing this same issue with a repo that uses and older version of Node - verified with Node 12.6 and 12.22

Swapping to Node 14.21 (without reinstalling packages) resolves the error

**Comment by brettz9** [comment]
Yeah, I think this must be due to the user using an unsupported version of Node (an `engines` warning might have shown earlier, but now it really won't work under older Node), so closing. Feel free to comment further as necessary.
